export const PERMISSIONS = {
  USERS_READ: "users:read",
  USERS_WRITE: "users:write",
  ROLES_READ: "roles:read",
  ROLES_WRITE: "roles:write",
  PROJECTS_READ: "projects:read",
  PROJECTS_WRITE: "projects:write",
  TASKS_READ: "tasks:read",
  TASKS_WRITE: "tasks:write",
  SKILLS_READ: "skills:read",
  SKILLS_WRITE: "skills:write",
  DEPARTMENTS_READ: "departments:read",
  DEPARTMENTS_WRITE: "departments:write",
  ALLOCATIONS_READ: "allocations:read",
  ALLOCATIONS_WRITE: "allocations:write",
  AVAILABILITY_READ: "availability:read",
  AVAILABILITY_WRITE: "availability:write",
  TIMESHEETS_READ: "timesheets:read",
  TIMESHEETS_WRITE: "timesheets:write",
  LEAVES_READ: "leaves:read",
  LEAVES_WRITE: "leaves:write",
  DASHBOARD_READ: "dashboard:read",
  ANALYTICS_READ: "analytics:read",
  SEARCH_READ: "search:read",
  REPORTS_READ: "reports:read",
  NOTIFICATIONS_READ: "notifications:read",
  NOTIFICATIONS_WRITE: "notifications:write",
  SETTINGS_READ: "settings:read",
  SETTINGS_WRITE: "settings:write",
  AUDIT_READ: "audit:read",
  PROJECT_REQUESTS_READ: "project-requests:read",
  PROJECT_REQUESTS_WRITE: "project-requests:write",
};



